#[build]
#target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
#rustflags = ["-C", "target-feature=-crt-static", "-C", "link-args=-static-libgcc", "-C", "link-arg=-nostartfiles", "-g"]
rustflags = ["-C", "target-feature=-crt-static", "-C", "link-args=-static-libgcc", "-C", "link-arg=-nostartfiles", "-C", "lto"]

